---
title: "Hepatocyte annotation"
author: "Miren Urrutia Iturritza"
date: "2023-06-01"
output: html_document
---

```{r setup}
#Setting the working directory
setwd("/corgi/miren/snseq_Ghent/cell_type_annotation/hepatocyte_annotation/")

#Load required libraries
library(scmap)
library(SingleCellExperiment)
library(Seurat)
library(scater)
```

```{r Load files}
#Read our data from Ghent
sce_snseq_curated_hepatocyte <- readRDS("/corgi/miren/snseq_Ghent/cell_type_annotation/hepatocyte_annotation/curated_merged_singleCellExperiment_only_hep.RDS")

#Format as desired
rowData(sce_snseq_curated_hepatocyte)$feature_symbol <- rownames(sce_snseq_curated_hepatocyte)
colData(sce_snseq_curated_hepatocyte)$cell_type1 <-sce_snseq_curated_hepatocyte@colData$ident
```

```{r Load files}
# Load reference data (the data that is already annotated)
sce_hepatocytes_MM <- readRDS("/corgi/miren/snseq_Ghent/cell_type_annotation/hepatocyte_annotation/SingleCellExperiment_CS_data.RDS")

#Format as desired
rowData(sce_hepatocytes_MM)$feature_symbol <- rownames(sce_hepatocytes_MM)
colData(sce_hepatocytes_MM)$cell_type1 <- sce_hepatocytes_MM@colData$ident
```

```{r HVGs}
#Load HVG
ftrs.file <- paste("/corgi/miren/snseq_Ghent/cell_type_annotation/hepatocyte_annotation/500_HDOgenes_ref_MM_hepatocytes.txt")

select.ftrs <- read.table(ftrs.file)$V1

genes_priority = c("Siglech", "Ly6d", "Ccr9", "Cd5l", "Clec4f", "Vsig4",
                             "Trbc2", "Cd3d", "Ms4a4b", "Lyz2", "Plac8", "Ms4a6c", "Xcl1",
                             "Ccl5",  "Igkc", "Cd79a", "Ighm", "H2-Eb", "H2-Aa",
                             "Cd74", "Gzma", "Nkg7", "S100a9", "S100a8", "Retnlg",
                             "Fscn1", "Ccr7", "Tmem123", "Cst3", "Naaa", "Ppt1", "Ptprb",
                             "Aqp1", "Clec4g", "Ghr", "Fabp1", "Aldob", "Spp1", "Clu", "Pkhd1",
                             "Rbms3", "Col14a1", "Lhfp", "Ccl3", "Hdc", "Osm", "Chrm3", "Slc4a4","Dmbt1")

#Set features to reference dataset
sce_hepatocytes_MM <- setFeatures(sce_hepatocytes_MM, features = c(select.ftrs, genes_priority))

#Calculate index
sce_hepatocytes_MM <- indexCell(sce_hepatocytes_MM)


# Extract the associated cell IDs from the reference and save as a variable
scmap_cell_metadata <- colData(sce_hepatocytes_MM)

#Project annotations
scmapCell_results <- scmapCell(
  sce_snseq_curated_hepatocyte,
  list(
   metadata(sce_hepatocytes_MM)$scmap_cell_index
  )
)

#Cluster annotation
scmapCell_clusters <- scmapCell2Cluster(
  scmapCell_results,
  list(
    as.character(colData(sce_hepatocytes_MM)$cell_type1)
  )
)

# Store this annotation information within the query object
colData(sce_snseq_curated_hepatocyte)$scmap_cluster <- scmapCell_clusters$scmap_cluster_labs

plotReducedDim(sce_snseq_curated_hepatocyte, dimred = "UMAP", colour_by = "scmap_cluster", text_by = "scmap_cluster", text_size = 3) + ggtitle(label ="Merged samples Steady State   colour: scmap_cluster, text = scmap_cluster")

plotReducedDim(sce_snseq_curated_hepatocyte, dimred = "UMAP", colour_by = "seurat_clusters", text_by = "scmap_cluster", text_size = 3)+ ggtitle(label ="Merged samples Steady State   colour: seurat_clusters, text = scmap_cluster")

plotReducedDim(sce_snseq_curated_hepatocyte, dimred = "UMAP", colour_by = "seurat_clusters", text_by = "seurat_clusters", text_size = 3)+ ggtitle(label ="Merged samples Steady State    colour: seurat_clusters, text = seurat_clusters")


length(which(sce_snseq_curated_hepatocyte$scmap_cluster !=  "NA")) / ncol(sce_snseq_curated_hepatocyte) * 100

par(mar = c(16, 10, 15, 7))
barplot_obj <- barplot(table(sce_snseq_curated_hepatocyte$scmap_cluster),
                       las = 2, 
                       main = "Merged samples cell proportions | Steady state reference", 
                       ylim = c(1, 100000), 
                       log = "y")

plot(
  getSankey(
    colData(sce_snseq_curated_hepatocyte)$ident,
    colData(sce_snseq_curated_hepatocyte)$scmap_cluster[,1],
    plot_height = 400, 
    colors = 
      c("#F8766D", "#E58700","#C99800","#A3A500","#6BB100", "#00BA38","#00BF7D",
        "#00C0AF","#00BCD8","#00B0F6","#619CFF","#B983FF","#E76BF3", "#FD61D1","#FF67A4")
      )
    )
```